version: '3.8'

services:
  client:
    image: bigboiearnes/gms-client:latest
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
    restart: unless-stopped

  server:
    image: bigboiearnes/gms-api:latest
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app/server
    restart: unless-stopped
